parameters:
    kernel.cache_dir: ~

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $cacheDir: '%kernel.cache_dir%'

    # create necessary aliases for auto-wiring
    Symfony\Component\HttpKernel\CacheClearer\CacheClearerInterface: '@cache_clearer'
    EzSystems\EzPlatformInstaller\API\Installer: '@EzSystems\EzPlatformInstaller\Core\Installer\CoreInstaller'

    EzSystems\EzPlatformInstallerBundle\Command\EzPlatformInstallCommand: ~
