services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformInstaller\API\Installer: '@EzSystems\EzPlatformInstaller\Core\Installer\CoreInstaller'
